import "server-only";
import { CATEGORIES, type Category, type ComponentSource, type RegistryEntry } from "./registry-types";
import index from "@/registry/__generated__/index.json";
import { proItemLoaders, sourceLoaders, thumbnails, videos } from "@/registry/__generated__/server-data";

const entries = index as RegistryEntry[];

export function allComponents(): RegistryEntry[] {
  return entries;
}

export function getComponent(slug: string): RegistryEntry | undefined {
  return entries.find((e) => e.slug === slug);
}

export function componentsIn(category: Category): RegistryEntry[] {
  return entries.filter((e) => e.category === category);
}

export function categoriesWithCounts() {
  return (Object.keys(CATEGORIES) as Category[])
    .map((key) => ({ key, ...CATEGORIES[key], count: entries.filter((e) => e.category === key).length }))
    .filter((c) => c.count > 0);
}

/** Code and prompts. Never call this for a Pro component without checking the licence. */
export async function readSource(slug: string): Promise<ComponentSource | null> {
  const load = Object.hasOwn(sourceLoaders, slug) ? sourceLoaders[slug] : undefined;
  return load ? ((await load()).default as ComponentSource) : null;
}

/** A Pro shadcn registry item. Check the licence first. */
export async function readProItem(slug: string): Promise<unknown | null> {
  const load = Object.hasOwn(proItemLoaders, slug) ? proItemLoaders[slug] : undefined;
  return load ? (await load()).default : null;
}

export function stats() {
  return {
    total: entries.length,
    free: entries.filter((e) => e.tier === "free").length,
    pro: entries.filter((e) => e.tier === "pro").length,
    mobile: entries.filter((e) => e.platform === "mobile").length,
  };
}

/** Static screenshot generated by scripts/screenshot.mjs, if present. */
export function thumbnailFor(slug: string): string | null {
  return thumbnails.has(`${slug}.webp`) ? `/previews/${slug}.webp` : null;
}

/** Hover video recorded by scripts/record-demos.mjs from meta.demo, if present. */
export function videoFor(slug: string): { mp4: string; webm: string | null } | null {
  if (!videos.has(`${slug}.mp4`)) return null;
  return { mp4: `/previews/${slug}.mp4`, webm: videos.has(`${slug}.webm`) ? `/previews/${slug}.webm` : null };
}

export type CardData = Pick<RegistryEntry, "slug" | "name" | "tier" | "platform" | "category" | "description" | "tags" | "theme" | "added"> & {
  thumb: string | null;
  video: { mp4: string; webm: string | null } | null;
};

export function toCard(e: RegistryEntry): CardData {
  return {
    slug: e.slug,
    name: e.name,
    tier: e.tier,
    platform: e.platform,
    category: e.category,
    description: e.description,
    tags: e.tags,
    theme: e.theme,
    added: e.added,
    thumb: thumbnailFor(e.slug),
    video: videoFor(e.slug),
  };
}
