import "server-only";
import fs from "node:fs";
import path from "node:path";
import { CATEGORIES, type Category, type ComponentSource, type RegistryEntry } from "./registry-types";
import index from "@/registry/__generated__/index.json";

const entries = index as RegistryEntry[];
const SOURCES = path.join(process.cwd(), "registry", "__generated__", "sources");

export function allComponents(): RegistryEntry[] {
  return entries;
}

export function getComponent(slug: string): RegistryEntry | undefined {
  return entries.find((e) => e.slug === slug);
}

export function componentsIn(category: Category): RegistryEntry[] {
  return entries.filter((e) => e.category === category);
}

export function categoriesWithCounts() {
  return (Object.keys(CATEGORIES) as Category[])
    .map((key) => ({ key, ...CATEGORIES[key], count: entries.filter((e) => e.category === key).length }))
    .filter((c) => c.count > 0);
}

/** Reads code and prompts. Never call this for a Pro component without checking the licence. */
export function readSource(slug: string): ComponentSource | null {
  const file = path.join(SOURCES, `${slug}.json`);
  if (!fs.existsSync(file)) return null;
  return JSON.parse(fs.readFileSync(file, "utf8")) as ComponentSource;
}

export function stats() {
  return {
    total: entries.length,
    free: entries.filter((e) => e.tier === "free").length,
    pro: entries.filter((e) => e.tier === "pro").length,
    mobile: entries.filter((e) => e.platform === "mobile").length,
  };
}

/** Static screenshot generated by scripts/screenshot.mjs, if present. */
export function thumbnailFor(slug: string): string | null {
  const file = path.join(process.cwd(), "public", "previews", `${slug}.webp`);
  return fs.existsSync(file) ? `/previews/${slug}.webp` : null;
}

export type CardData = Pick<RegistryEntry, "slug" | "name" | "tier" | "platform" | "category" | "description" | "tags" | "theme" | "added"> & {
  thumb: string | null;
};

export function toCard(e: RegistryEntry): CardData {
  return {
    slug: e.slug,
    name: e.name,
    tier: e.tier,
    platform: e.platform,
    category: e.category,
    description: e.description,
    tags: e.tags,
    theme: e.theme,
    added: e.added,
    thumb: thumbnailFor(e.slug),
  };
}
